# Generated by Django 5.0.6 on 2024-06-11 05:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_tag_remove_blog_category_delete_categories_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(unique=True),
        ),
    ]
