# Generated by Django 5.0.6 on 2024-06-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='This Blog does not have description', max_length=20),
        ),
    ]
